### ISSUE TITLE
Embedded video disabled

### ISSUE THREAD

**Issue by YannAries** [hewillnotdivideus/hewillnotdivideus.github.io#1]
Issue with the embedded video player being disabled.

**Comment by BubuAnabelas** [comment]
I'm aware of this, I send a [tweet](https://twitter.com/BubuAnabelas/status/827049827427037186) to Luke Turner yesterday but didn't get a response.
There isn't anything I can really do to fix it, since the page it's blocked from the streaming configuration (livestream.com).
I'll try to find a workarround but I seriously doubt I can fix this.

In the mean time you could fork the repository locally and run the page on your computer.
